### ISSUE TITLE
Fails to compile on new rust(greater than 1.46?)

### ISSUE THREAD

**Issue by pyrox0** [xermicus/blindspot#4]
I tested this on 1.50, 1.51, 1.47, and 1.46, and this does not compile.
Here is the error that was spit out each time.
```
error[E0432]: unresolved imports `async_std::sync::channel`, `async_std::sync::Receiver`, `async_std::sync::RecvError`, `async_std::sync::Sender`
 --> /Users/993390/.cargo/registry/src/github.com-1ecc6299db9ec823/blindspot-1.2.0/src/bspm/ui.rs:4:23
  |
4 | use async_std::sync::{channel, Mutex, Receiver, RecvError, Sender};
  |                       ^^^^^^^         ^^^^^^^^  ^^^^^^^^^  ^^^^^^ no `Sender` in `sync`
  |                       |               |         |
  |                       |               |         no `RecvError` in `sync`
  |                       |               no `Receiver` in `sync`
  |                       no `channel` in `sync`

error[E0277]: can't compare `()` with `&str`
  --> /Users/993390/.cargo/registry/src/github.com-1ecc6299db9ec823/blindspot-1.2.0/src/bspm/mod.rs:97:76
   |
97 |             if !force && ctx.ask("Enter `y` to force installation").await? != "y" {
   |                                                                            ^^ no implementation for `() == &str`
   |
   = help: the trait `std::cmp::PartialEq<&str>` is not implemented for `()`

error[E0282]: type annotations needed
   --> /Users/993390/.cargo/registry/src/github.com-1ecc6299db9ec823/blindspot-1.2.0/src/bspm/ui.rs:214:24
    |
214 |             let line = input.trim();
    |                        ^^^^^ cannot infer type
    |
    = note: type must be known at this point

error[E0282]: type annotations needed
   --> /Users/993390/.cargo/registry/src/github.com-1ecc6299db9ec823/blindspot-1.2.0/src/cmd.rs:138:9
    |
138 |         ui::context("", "").await.quit().await?;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0277, E0282, E0432.
For more information about an error, try `rustc --explain E0277`.
error: failed to compile `blindspot v1.2.0`, intermediate artifacts can be found at `/var/folders/gb/bhwrt1rn7fb56vggfct3hlx80000gq/T/cargo-installT4WbqS`

Caused by:
  could not compile `blindspot`.
```

**Comment by xermicus** [comment]
Hi, thank you so much for reporting this! Looks like something broke with dependencies. Just pushed a fix, you should be able to compile again @ModdedGamers ?

**Comment by pyrox0** [comment]
This works! Thank you so much!
